#!/usr/local/bin/ruby

require 'optparse'
BUILDER_OPTIONS = {
  :environment     => "development"
}

ARGV.options do |opts|
  opts.on("-e", "--environment=name", String,
          "Specifies the environment to run this server under (test/development/production).",
          "Default: development") { |BUILDER_OPTIONS[:environment]| }
end

ENV["RAILS_ENV"] = BUILDER_OPTIONS[:environment]
require File.dirname(__FILE__) + "/../config/environment"

# set up logging
[
  DamageControl::ScmPoller,
  DamageControl::BuildDaemon, 
  DamageControl::Publisher::Base, 
  Build, 
  Project, 
  Revision
].each { |cls| cls.logger = Logger.new(STDOUT) }
 
DamageControl::BuildDaemon.new(DamageControl::ScmPoller.new).run
