#!/usr/local/bin/ruby

# BIG TODO: set env in one place only. init.rb or script/damagecontrol. also think about easy ror upgrade!
ENV["RAILS_ENV"] = "development"
require File.dirname(__FILE__) + "/../config/environment"

# set up logging
[
  DamageControl::ScmPoller, # TODO: This class is deprecated
  DamageControl::BuildDaemon, 
  DamageControl::Publisher::Base, 
  Build, 
  Project, 
  Revision
].each { |cls| cls.logger = Logger.new(STDOUT) }
 
DamageControl::BuildDaemon.new(DamageControl::ScmPoller.new).run
