#!/usr/local/bin/ruby

load File.dirname(__FILE__) + '/../config/dc_environment.rb'

# We want notification for all states of a build
all_build_states = [
  Build::Executing.new,
  Build::Successful.new,
  Build::Fixed.new,
  Build::Broken.new,
  Build::RepeatedlyBroken.new
]
growl = DamageControl::Publisher::Growl.new

# Create some default projects

if(!Project.find_by_name("RSCM (trunk)"))
  rscm = Project.create(
    :name => "RSCM (trunk)",
    :home_page => "http://rscm.rubyforge.org/",
    :start_time => 2.weeks.ago.utc, 
    :relative_build_path => "", 
    :build_command => "rake", 
    :scm => RSCM::Subversion.new("svn://beaver.codehaus.org/damagecontrol/scm/trunk/rscm")
  )
  
  rscm.publishers.create(:delegate => growl, :enabling_states => all_build_states)
end

if(!Project.find_by_name("DamageControl (damagecontrol_active_record branch)"))
  damagecontrol_ar = Project.create(
    :name => "DamageControl (damagecontrol_active_record branch)",
    :home_page => "http://hieraki.lavalamp.ca/",
    :start_time => 2.weeks.ago.utc, 
    :relative_build_path => "", 
    :build_command => "rake", 
    :scm => RSCM::Subversion.new("svn://beaver.codehaus.org/damagecontrol/scm/branches/damagecontrol_active_record")
  )

  damagecontrol_ar.publishers.create(:delegate => growl, :enabling_states => all_build_states)
  damagecontrol_ar.dependencies << rscm
  damagecontrol_ar.save
end

if(!Project.find_by_name("DamageControl (trunk)"))
  damagecontrol = Project.create(
    :name => "DamageControl (trunk)",
    :home_page => "http://hieraki.lavalamp.ca/",
    :start_time => 2.weeks.ago.utc, 
    :relative_build_path => "", 
    :build_command => "rake", 
    :scm => RSCM::Subversion.new("svn://beaver.codehaus.org/damagecontrol/scm/trunk/damagecontrol")
  )

  damagecontrol.publishers.create(:delegate => growl, :enabling_states => all_build_states)
end

if(!Project.find_by_name("Ruby (trunk)"))
  ruby = Project.create(
    :name => "Ruby (trunk)",
    :home_page => "http://ruby-lang.org/",
    :start_time => 2.weeks.ago.utc, 
    :relative_build_path => "", 
    :build_command => "autoconf;./configure;make", 
    :scm => RSCM::Cvs.new(":pserver:anonymous@cvs.ruby-lang.org:/src", "ruby")
  )

  ruby.publishers.create(:delegate => growl, :enabling_states => all_build_states)
end

