#!/usr/local/bin/ruby

load File.dirname(__FILE__) + '/../config/environment.rb'

# set up logging
[DamageControl::ScmPoller, 
DamageControl::Publisher::Base, 
Build, 
Project, 
Revision].each { |cls| cls.logger = Logger.new(STDOUT) }
 
DamageControl::BuildDaemon.new.run
