#!/usr/local/bin/ruby

# This script slurps a YAML file from stdin and sets up a new (or, modifies an existing) 
# DamageControl project. Useful for setting up projects in an automated fashion.
#
# Usage:
#
# ruby script/importer < path/to/project/yaml/file
#
# See the example YAML file in this directory for an example.

begin
  require File.dirname(__FILE__) + "/../config/environment"
  project_hash = YAML.load(STDIN)

  project = nil
  if(project_hash[:id])
    project = Project.find(project_hash[:id])
    puts "Updating existing project '#{project.name}'"
  else
    puts "Creating new project"
    project = Project.create(project_hash[:id])
  end
  project.populate_from_hash(project_hash)
  project.save
rescue => e
  STDERR.puts e.message
  STDERR.puts e.backtrace.join("\n")
  exit 1
end