#!/usr/bin/ruby

# This script slurps a Project configuration in YAML from a file or a URL and sets up a new 
# (or, modifies an existing) DamageControl project. Useful for setting up projects in an 
# automated fashion.
#
# Usage:
#
# ruby script/importer path/to/project/yaml/file
# ruby script/importer http://some.host/path/to/project/yaml/file
#
# See the example YAML file in this directory for an example.

require 'open-uri'
begin
  require File.dirname(__FILE__) + "/../config/environment"
  
  opener = ARGV[0] =~ /^http/ ? Kernel : File
  opener.open(ARGV[0]) do |io|
    project_hash = YAML.load(io)

    project = Project.find_by_name(project_hash['name'])
    if(project)
      STDOUT.puts "Updating existing project #{project_hash['name']}"
    else
      STDOUT.puts "Creating new project #{project_hash['name']}"
      project = Project.create
    end
    project.populate_from_hash(project_hash, nil)
    project.save
  end
rescue => e
  STDERR.puts e.message
  STDERR.puts e.backtrace.join("\n")
  exit 1
end