#!/usr/local/bin/ruby

require 'optparse'

ENV['RAILS_ENV'] = "development"
ARGV.options do |opts|
  script_name = File.basename($0)
  opts.banner = "Usage: ruby #{script_name} [options]"

  opts.on("-e", "--environment=name", String,
          "Specifies the environment (test/development/production).",
          "Default: #{ENV['RAILS_ENV']}") { |ENV['RAILS_ENV']|}

  opts.separator ""
  opts.on("-h", "--help",
          "Show this help message.") { puts opts; exit }

  opts.parse!
end
require File.dirname(__FILE__) + "/../config/environment"

# set up logging
FileUtils.mkdir_p("#{DC_DATA_DIR}/log") unless File.exist?("#{DC_DATA_DIR}/log")
logfile = "#{DC_DATA_DIR}/log/scm_poller.log"
logger = Logger.new(logfile, 10, 1.megabyte)
logger.datetime_format = "%Y-%m-%d %H:%M:%S"
logger.level = Logger::DEBUG
[
  DamageControl::Process::ScmPoller,
  Project, 
  Revision
].each { |cls| cls.logger = logger }
puts "DamageControl scm_poller log: #{logfile}"
DamageControl::Process::ScmPoller.new.run
