require 'rubygems'
require 'rake'
require 'rake/testtask'
require 'rake/rdoctask'
require 'rake/packagetask'
require 'rake/gempackagetask'
require 'rake/contrib/rubyforgepublisher'

PKG_BUILD     = ENV['PKG_BUILD'] ? '.' + ENV['PKG_BUILD'] : ''
PKG_NAME      = 'damagecontrol'
PKG_VERSION   = '0.5.0' + PKG_BUILD
PKG_FILE_NAME = "#{PKG_NAME}-#{PKG_VERSION}"

desc "Default Task"
task :default => [ :all ]

# Run the unit tests
# To run a specific test: rake test TEST=path/to/test
fl = FileList.new('test/**/*_test.rb')
Rake::TestTask.new { |t|
  # We need some of the test utils from rscm
  t.libs << "test" << File.expand_path(File.dirname(__FILE__) + "/../rscm/test")
  t.test_files = fl
  t.verbose = true
}

rd = Rake::RDocTask.new { |rdoc|
  rdoc.rdoc_dir = 'doc'
  rdoc.title    = 'DamageControl - Cross platform Continuous Integration server'
  rdoc.options << '--line-numbers' << '--inline-source'
  rdoc.rdoc_files.include('README')
  rdoc.rdoc_files.include('lib/**/*.rb')
  rdoc.rdoc_files.include('docs/**/*.rd')
}

task :all => [:gem]

PKG_FILES = FileList[
  '[A-Z]*',
  'doc/**/*',
  'app/**/*',
  'config/**/*',
  'docs/**/*',
  'lib/**/*.rb', 
  'public/**/*',
  'script/**/*.*',
  'test/**/*.*'
]

if ! defined?(Gem)
  puts "Package Target requires RubyGEMs"
else
  spec = Gem::Specification.new do |s|
    
    #### Basic information.

    s.name = 'damagecontrol'
    s.version = PKG_VERSION
    s.summary = "DamageControl"
    s.description = <<-EOF
      DamageControl.
    EOF

    #### Dependencies and requirements.

    s.add_dependency('log4r', '> 1.0.4')
    s.add_dependency('rscm')
    s.add_dependency('rgl')
    #s.requirements << ""

    #### Which files are to be included in this gem?  Everything!  (Except CVS directories.)

    s.files = PKG_FILES.to_a

    #### C code extensions.

    #s.extensions << "ext/rmagic/extconf.rb"

    #### Load-time details: library and application (you will need one or both).

    s.require_path = 'lib'                         # Use these for libraries.
    s.autorequire = 'rscm'

    #s.bindir = "bin"                               # Use these for applications.
    #s.executables = ["rscm"]
    #s.default_executable = "rscm"

    #### Documentation and testing.

    s.has_rdoc = true
    s.extra_rdoc_files = rd.rdoc_files.reject { |fn| fn =~ /\.rb$/ }.to_a
    rd.options.each do |op|
      s.rdoc_options << op
    end

    #### Author and project details.

    s.author = "Aslak Hellesoy"
    s.email = "dev@damagecontrol.codehaus.org"
    s.homepage = "http://damagecontrol.codehaus.org/rscm"
    s.rubyforge_project = "rscm"
  end

  Rake::GemPackageTask.new(spec) do |pkg|
    pkg.need_zip = true
    pkg.need_tar = true
  end
end
