$:<<'../../lib'

require 'damagecontrol/FilePollerTest'
require 'damagecontrol/EqualityTest'
#require 'damagecontrol/CruiseControlBridgeTest'
require 'damagecontrol/CruiseControlLogPollerTest'
require 'damagecontrol/AsyncComponentTest'
require 'damagecontrol/IRCPublisherTest'
require 'damagecontrol/BuildTest'
require 'damagecontrol/HubTest'
require 'damagecontrol/BuildDelayerTest'
require 'damagecontrol/WebsitePublisherTest'
require 'damagecontrol/BuildExecutorTest'
require 'damagecontrol/TimerTest'
require 'damagecontrol/LogWriterTest'
#require 'damagecontrol/CVSPollerTest'
require 'damagecontrol/dependency/AllTraverserTest'
require 'damagecontrol/dependency/UpstreamDownstreamTraverserTest'
