$:<<'../../lib'

require 'damagecontrol/FilePollerTest'
require 'damagecontrol/EqualityTest'
require 'damagecontrol/AsyncComponentTest'
require 'damagecontrol/BuildTest'
require 'damagecontrol/HubTest'
require 'damagecontrol/BuildDelayerTest'
require 'damagecontrol/BuildExecutorTest'
require 'damagecontrol/TimerTest'
require 'damagecontrol/LogWriterTest'

require 'damagecontrol/publisher/IRCPublisherTest'
require 'damagecontrol/publisher/WebsitePublisherTest'
require 'damagecontrol/publisher/HTMLPublisherTest'
#require 'damagecontrol/CVSPollerTest'
require 'damagecontrol/dependency/AllTraverserTest'
require 'damagecontrol/dependency/UpstreamDownstreamTraverserTest'

#require 'damagecontrol/CruiseControlBridgeTest'
require 'damagecontrol/cruisecontrol/CruiseControlLogPollerTest'
