require 'rubygems'
require 'rake'
require 'rake/testtask'
require 'rake/rdoctask'
require 'rake/packagetask'
require 'rake/gempackagetask'
require 'rake/contrib/rubyforgepublisher'

PKG_BUILD     = ENV['PKG_BUILD'] ? '.' + ENV['PKG_BUILD'] : ''
PKG_NAME      = 'rscm'
PKG_VERSION   = '0.1.0' + PKG_BUILD
PKG_FILE_NAME = "#{PKG_NAME}-#{PKG_VERSION}"

desc "Default Task"
task :default => [ :test ]

# Run the unit tests
# To run a specific test: rake test TEST_FILES=<some glob>
test_file_pattern = ENV["TEST_FILES"] ? ENV["TEST_FILES"] : 'test/**/*_test.rb'
fl = FileList.new(test_file_pattern)
fl.exclude('test/**/mooky*.rb') unless ENV["TEST_FILES"]
Rake::TestTask.new { |t|
  t.libs << "test"
  t.test_files = fl
  t.verbose = true
}

Rake::RDocTask.new { |rdoc|
  rdoc.rdoc_dir = 'doc'
  rdoc.title    = "RSCM - Ruby Source Control Management API"
  rdoc.options << '--line-numbers --inline-source --main README'
  rdoc.rdoc_files.include('README')
  rdoc.rdoc_files.include('lib/**/*.rb')
}

