development:
  adapter: sqlite3
  dbfile: <%= DC_DATA_DIR %>/db/development.db

test:
  adapter: sqlite3
  dbfile: <%= DC_DATA_DIR %>/db/test.db

production:
  adapter: sqlite3
  dbfile: <%= DC_DATA_DIR %>/db/production.db
