DC_LIBS = ["lib", "../../trunk/rscm/lib", "../../trunk/rscm/test", "vendor/rscm/lib"]
$:.unshift(DC_LIBS.collect{|p| RAILS_ROOT+"/"+p}.join(':'))

DC_DATA_DIR = File.expand_path(SHELL_DIR) unless defined? DC_DATA_DIR
# Require this file if it exists (it is generated by dist.rake)
require 'damagecontrol'
