#!/usr/local/bin/ruby

raise "This script must be run via script/damagecontrol" unless defined? DC_ENV
ENV["RAILS_ENV"] = DC_ENV[:environment]
require File.dirname(__FILE__) + "/../config/environment"

# set up logging
[
  DamageControl::ScmPoller,
  DamageControl::BuildDaemon, 
  DamageControl::Publisher::Base, 
  Build, 
  Project, 
  Revision
].each { |cls| cls.logger = Logger.new(STDOUT) }
 
DamageControl::BuildDaemon.new(DamageControl::ScmPoller.new).run
