#!/usr/local/bin/ruby

load File.dirname(__FILE__) + '/../config/dc_environment.rb'

scm_poller_thread = Thread.new do
  scm_poller = DamageControl::ScmPoller.new
  scm_poller.poll_all_projects
end
puts "DamageControl daemon started"
scm_poller_thread.join