#!/usr/local/bin/ruby

# This script slurps a YAML file from stdin and sets up a new (or, modifies an existing) 
# DamageControl project. Useful for setting up projects in an automated fashion.
#
# Usage:
#
# ruby script/importer < path/to/project/yaml/file
#
# See the example YAML file in this directory for an example.

require File.dirname(__FILE__) + "/../config/environment"
project_hash = YAML.load(STDIN)

project = nil
if(project_hash[:project][:id])
  puts "Updating existing project with id=#{project_hash[:project][:id]}"
  project = Project.find(project_hash[:project][:id])
else
  puts "Creating new project"
  project = Project.create(project_hash[:project][:id])
end
project.populate_from_hash(project_hash)
project.save