development:
  adapter: sqlite
  dbfile: <%= SHELL_DIR %>/db/development.db

test:
  adapter: sqlite
  dbfile: <%= SHELL_DIR %>/db/test.db

production:
  adapter: sqlite
  dbfile: <%= SHELL_DIR %>/db/production.db