DC_LIBS = ["lib", "../../trunk/rscm/lib", "../../trunk/rscm/test", "vendor/rscm/lib"]
$:.unshift(DC_LIBS.collect{|p| RAILS_ROOT+"/"+p}.join(':'))

# Require this file if it exists (it is generated by dist.rake)
require 'damagecontrol'
